version: '3.8'

networks:
  stokei-network:
    driver: bridge

volumes:
  redis-data:
  storage-dev-data:

services:
  redis:
    image: bitnami/redis:7.0.15
    container_name: redis
    environment:
      REDIS_PASSWORD: 'redis'
    ports:
      - '16379:6379'
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - stokei-network
  storage-dev:
    container_name: storage-dev
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - storage-dev-data:/data
