networks:
  stokei-network:
    driver: bridge

volumes:
  redis-data:
  storage-dev-data:

services:
  video-transcoder-api:
    image: stokei/video-transcoder-api:latest
    container_name: video-transcoder-api
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - storage-dev
    networks:
      - stokei-network
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
      URL: ${URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      STORAGE_KEY: ${STORAGE_KEY}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_REGION: ${STORAGE_REGION}

  redis:
    image: bitnami/redis:7.0.15
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - stokei-network

  storage-dev:
    image: minio/minio
    container_name: storage-dev
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - stokei-network
    environment:
      - MINIO_ROOT_USER=${STORAGE_DEV_USERNAME}
      - MINIO_ROOT_PASSWORD=${STORAGE_DEV_PASSWORD}
    volumes:
      - storage-dev-data:/data
